Parameters:
  Region: "cn-hangzhou"
  Name: "oss-website"
  GatewayId: gw-cu9g7dem1hkn32ee70bg
  EnvironmentId: env-cu9g82mm1hkui0vcv5eg
SceneProfiles:
  - DisplayName:
      zh-cn: 基于云原生 API 网关和阿里云 OSS 实现前端网站托管
      en: Oss Website
    Template: "templates/msa.yml"
    Parameters:
      Service:
        Name: "oss-website"
        OssBucketName: "apig-oss-integration"