Parameters:
  Region: "cn-hangzhou"
  GatewayId: gw-cu9g7dem1hkn32ee70bg
  EnvironmentId: env-cu9g82mm1hkui0vcv5eg
  Name: "nginx-migrate-apig"
SceneProfiles:
  - DisplayName:
      zh-cn: Nginx 前端应用迁移到云原生API网关
      en: Nginx Migrate Apig
    Template: "templates/msa.yml"
    Parameters:
      Backend:
        Handler: index.handler
