Parameters:
  Region: "cn-hangzhou"
  Name: "basic-auth-plugin"
SceneProfiles:
  - DisplayName:
      zh-cn: Nginx前端应用迁移到云原生API网关
      en: Nginx Migrate Apig
    Template: "templates/msa.yml"
    Parameters:
      HttpApi:
        GatewayId: gw-cu9g7dem1hkn32ee70bg
        EnvironmentId: env-cu9g82mm1hkui0vcv5eg
      Backend:
        Cpu: 1
        Memory: 4096
        Handler: index.handler
